<?php
/**
 * SuscriberStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Easymailing API
 *
 * The Easymailing API is a set of REST APIs that enable you to programmatically manage Campaign, Audience, Suscribers, Stats and more.\\ The Easymailing API is organized around REST. Our API has predictable resource-oriented URLs and uses standard HTTP response codes, authentication, and verbs\\ This documents all the REST API methods, with example requests and responses. You can also load this into the Postman API Development Environment to interact with the API with your own Bearer tokens.\\ If there are other uses cases you'd like the API to support, please [contact us](https://ayuda.easymailing.com).
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * SuscriberStatus Class Doc Comment
 *
 * @category Class
 * @description Suscriber status: * &#x60;suscriber.status.confirmed&#x60; - Confirmed and active * &#x60;suscriber.status.unsuscribed&#x60; - Unsubscribed by contact * &#x60;suscriber.status.unsuscribed.admin&#x60; - Unsubscribed by admin
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SuscriberStatus
{
    /**
     * Possible values of this enum
     */
    const CONFIRMED = 'suscriber.status.confirmed';
const UNSUSCRIBED = 'suscriber.status.unsuscribed';
const UNSUSCRIBEDADMIN = 'suscriber.status.unsuscribed.admin';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONFIRMED,
self::UNSUSCRIBED,
self::UNSUSCRIBEDADMIN,        ];
    }
}
