<?php
/**
 * AudienceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Easymailing API
 *
 * The Easymailing API is a set of REST APIs that enable you to programmatically manage Campaign, Audience, Suscribers, Stats and more.\\ The Easymailing API is organized around REST. Our API has predictable resource-oriented URLs and uses standard HTTP response codes, authentication, and verbs\\ This documents all the REST API methods, with example requests and responses. You can also load this into the Postman API Development Environment to interact with the API with your own Bearer tokens.\\ If there are other uses cases you'd like the API to support, please [contact us](https://ayuda.easymailing.com).
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * AudienceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AudienceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getListDistributionCollection
     *
     * Retrieves the collection of ListDistribution resources..
     *
     */
    public function testGetListDistributionCollection()
    {
    }

    /**
     * Test case for getListDistributionItem
     *
     * Retrieves a ListDistribution resource..
     *
     */
    public function testGetListDistributionItem()
    {
    }

    /**
     * Test case for getListFieldCollection
     *
     * Retrieves the collection of ListField resources..
     *
     */
    public function testGetListFieldCollection()
    {
    }

    /**
     * Test case for getListFieldItem
     *
     * Retrieves a ListField resource..
     *
     */
    public function testGetListFieldItem()
    {
    }

    /**
     * Test case for getListFieldValueCollection
     *
     * Retrieves the collection of ListFieldValue resources..
     *
     */
    public function testGetListFieldValueCollection()
    {
    }

    /**
     * Test case for getListFieldValueItem
     *
     * Retrieves a ListFieldValue resource..
     *
     */
    public function testGetListFieldValueItem()
    {
    }

    /**
     * Test case for getListSegmentCollection
     *
     * Retrieves the collection of ListSegment resources..
     *
     */
    public function testGetListSegmentCollection()
    {
    }

    /**
     * Test case for getListSegmentItem
     *
     * Retrieves a ListSegment resource..
     *
     */
    public function testGetListSegmentItem()
    {
    }

    /**
     * Test case for postListFieldCollection
     *
     * Creates a ListField resource..
     *
     */
    public function testPostListFieldCollection()
    {
    }
}
